name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@main

      - name: Initialization Variables
        run: |
          echo "Free space:"
          df -h
          pwd
          ls -al
          id
          echo $USER
          echo $GROUPS
          echo $PWD
          echo $GITHUB_WORKSPACE
          echo $GITHUB_ENV
          cat $GITHUB_ENV
          
